name: Validate Data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
      - run: yarn --frozen-lockfile
      - name: Validate
        env: 
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: yarn validate ${ALL_CHANGED_FILES}
